title: ALEX Version History
description: ALEX Version History
theme: just-the-docs
logo: "/assets/images/ALEX.png"
favicon_ico: "/assets/images/favicon_ico.png"

url: https://quatmax.github.io/alex-version-history

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
