title: ALEX Version History
description: ALEX Version History
theme: just-the-docs
logo: "/assets/images/alex.svg"
favicon_ico: "/assets/images/favicon.ico"
color_scheme: dark

url: https://quatmax.github.io/alex-version-history

aux_links:
  ALEX Wiki: https://alexwiki.bitfactory.at

aux_links_new_tab: true

search_enabled: true