title: ALEX Version History
description: ALEX Version History
theme: just-the-docs
logo: "/assets/images/ALEX.png"
favicon_ico: "/assets/images/favicon.ico"

url: https://quatmax.github.io/alex-version-history

aux_links:
  BitFactory: https://bitfactory.at

search_enabled: true